"""Add attendance_anomaly table

Revision ID: 9cab21ae9fcc
Revises: c0f8a7ace853
Create Date: 2026-05-02 09:40:46.033801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cab21ae9fcc'
down_revision = 'c0f8a7ace853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_anomaly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anomaly_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('affected_student_id', sa.Integer(), nullable=True),
    sa.Column('affected_faculty_id', sa.Integer(), nullable=True),
    sa.Column('affected_course_id', sa.Integer(), nullable=True),
    sa.Column('affected_section_id', sa.Integer(), nullable=True),
    sa.Column('date_detected', sa.DateTime(), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('dismissed_by', sa.String(length=100), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_anomaly')
    # ### end Alembic commands ###
